version: '3.2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    volumes:
#      - /application/data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet.network
        
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_HOSTS: 0
    depends_on:
      - elasticsearch
    networks:
      - esnet.network

  api:
    build:
      context: .
      dockerfile: ElasticSearchExample/Dockerfile
    container_name: api
    restart: always
    ports:
      - "88:80"
    depends_on:
      - elasticsearch
    networks:
      - esnet.network

networks:
  esnet.network:
    driver: bridge



