version: '3.2'

services:

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /application/data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet.network

  api:
    build:
      context: .
      dockerfile: ElasticSearchExample/Dockerfile
    container_name: api
    restart: always
    ports:
      - "88:80"
    depends_on:
      - es
    networks:
      - esnet.network

networks:
  esnet.network:
    driver: bridge



